---
label: default
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  label: Publish Date
  name: publish_date
  config:
    required: true
- type: text
  label: layout
  name: layout
  hidden: true
